// ─────────────────────────────────────────────────────────────────────────────
// The Story Director's genre vocabulary.
//
// GENERATED by tools/port-shared.mjs from features/storyplan/ui.js — edit it
// there, not here.
//
// Data, not UI. It lives in the tab upstream because the tab was its only
// reader, but the interceptor also names a genre when it builds the director's
// prompt, and that runs in the backend, which cannot import a file that touches
// the DOM.
// ─────────────────────────────────────────────────────────────────────────────

export const SD_GENRES = {
    "slice-of-life": { label: "Slice of Life", desc: "Daily rhythms, small moments, character-driven warmth." },
    "drama": { label: "Drama", desc: "Emotional conflict, relationship tension, high stakes feelings." },
    "romance": { label: "Romance", desc: "Love as the central engine — pursuit, longing, devotion." },
    "action": { label: "Action / Adventure", desc: "Physical danger, quests, combat, exploration." },
    "mystery": { label: "Mystery / Thriller", desc: "Secrets, investigation, paranoia, carefully timed reveals." },
    "fantasy": { label: "Fantasy / RPG", desc: "Magic systems, world-building, quests, power progression." },
    "horror": { label: "Horror / Dark", desc: "Dread, survival, psychological terror, body horror." },
    "scifi": { label: "Sci-Fi", desc: "Technology, space, dystopia, transhumanism." },
    "comedy": { label: "Comedy", desc: "Humor-driven, absurdist, sitcom energy, comedic timing." },
    // Added from reader answers. Deliberately only the ones the nine above do not
    // already cover: Thriller lives inside Mystery, Adventure inside Action and
    // RPG inside Fantasy, so adding them again would be three ways to say the
    // same thing in one dropdown.
    "anime": { label: "Anime / Light Novel", desc: "Genre-savvy tropes, ensemble cast, escalating arcs, tonal swings played straight." },
    "tabletop": { label: "Tabletop RPG", desc: "D&D, Delta Green, Call of Cthulhu — a party, a table, and a world that answers to rules." },
    "psychological": { label: "Psychological", desc: "Interior pressure, unreliable perception, obsession, a slow unravelling." },
    "freeform": { label: "Free-form", desc: "No genre conventions imposed. The story goes wherever the scene takes it." }
};

export const SD_CUSTOM_GENRE = "custom";

export function sdGenreLabel(sp) {
    if (!sp) return "Drama";
    if (sp.primaryGenre === SD_CUSTOM_GENRE) {
        const typed = String(sp.customGenre || "").trim();
        return typed || "Drama";
    }
    return SD_GENRES[sp.primaryGenre]?.label || "Drama";
}
