// Turns style.css into a JS module exporting it as a string.
//
// ctx.dom.addStyle() wants CSS as a string, and the bundler has no business
// deciding how a stylesheet reaches the browser when the host is the one that
// injects it. Generating a module keeps the stylesheet a plain .css file that an
// editor can still highlight, while the bundle sees ordinary JS.
//
// Run by `npm run build` before bun; the generated file is gitignored.

import { readFileSync, writeFileSync } from "node:fs";

const css = readFileSync(new URL("../style.css", import.meta.url), "utf8");

writeFileSync(
    new URL("../src/frontend/styles.generated.js", import.meta.url),
    `// GENERATED by tools/embed-styles.mjs — do not edit. Edit style.css instead.\n`
    + `export const MEGUMIN_STYLES = ${JSON.stringify(css)};\n`,
);

console.log(`embedded style.css (${(css.length / 1024).toFixed(0)}KB)`);
